services:
  backend:
    build: ./backend
    env_file: .env
    ports:
      - "8080:8080"
    networks:
      - s3drive-network

  frontend:
    build: ./frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - s3drive-network

networks:
  s3drive-network:
    driver: bridge