spring.application.name=s3dback

aws.accessKeyId=${AWS_ACCESS_KEY}
aws.secretKey=${AWS_SECRET_KEY}
aws.region=${AWS_REGION}
aws.bucketName=${AWS_BUCKET_NAME}
cors.allowed-origins=${ALLOWED_ORIGINS}
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB